### ISSUE TITLE
Support inline definition

### ISSUE THREAD

**Issue by vdemeester** [vdemeester/tkn-local-action#4]
```yaml
    - uses: vdemeester/tkn-local-action@main
      with:
        inline: |
          apiVersion: tekton.dev/v1beta1
          kind: TaskRun
          metadata:
            name: test
          spec:
            # […]
```
